name: openmpi
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python and scientific computing
  - python=3.12
  - numpy>=1.21.0
  - psutil>=5.8.0
  
  # MPI and networking
  - mpi4py>=3.1.0
  - openmpi>=4.1.4
  
  # GPU computing (PyTorch with CUDA support)
  - pytorch>=2.0.0
  - pytorch-cuda>=12.1
  
  # Additional useful packages
  - networkx>=3.0
  - matplotlib>=3.5.0
  - pandas>=1.5.0
  
  # Development and debugging tools
  - ipython>=8.0.0
  - jupyter>=1.0.0
  
  # System utilities
  - tmux>=3.0
  
  # Pip packages for additional functionality
  - pip
  - pip:
    # GPU monitoring and diagnostics
    - pynvml>=11.0.0
    
    # Additional PyTorch components
    - torchvision
    - torchaudio
    
    # Network testing utilities
    - netifaces>=0.11.0
    
    # Performance monitoring
    - psutil>=5.8.0
    
    # Optional: Additional scientific computing
    - scipy>=1.9.0
    - scikit-learn>=1.1.0